Repository AI-Expo-2023/Chromatica-BackEnd, pull requests merged in 2023-04, with the labels that each got.

#22 :bug: updated userPhoto bug fixed
  src/controller/user.js
  src/middleware/multer.js
  src/models/user.js
Labels: bug

#20 :bug: Updated sendEmail buf fixed
  src/.gitignore
  src/controller/user.js
  src/middleware/email.js
  src/package.json
  src/yarn.lock
Labels: bug

#24 ✨ :: created deleteUser func
  src/controller/user.js
  src/router/user.js
Labels: func

#26 :sparkles: :: create getUser
  src/controller/user.js
  src/router/user.js
Labels: func

#28 :sparkles: :: create findPW func
  src/controller/user.js
  src/router/user.js
Labels: func

#30 :sparkles: :: create getOtherUser func
  src/controller/user.js
  src/router/user.js
Labels: func

#31 :sparkles: :: created saveImage func
  src/controller/design.js
  src/models/design.js
  src/models/index.js
  src/router/design.js
  src/router/index.js
  src/router/user.js
Labels: func, DB

#33 :sparkles: :: create updateUserInfo func
  src/controller/user.js
  src/router/user.js
Labels: func

#35 :sparkles: :: create updatePW func
  src/controller/user.js
  src/router/user.js
Labels: func

#37 ✨ :: create otherUserImage
  src/controller/user.js
  src/models/index.js
  src/models/photo.js
  src/router/user.js
Labels: func, DB

#41 :sparkles: :: updated likedPhoto func
  src/controller/user.js
Labels: bug

#43 :sparkles: :: created myPhoto func
  src/controller/user.js
  src/router/user.js
Labels: func

#45 :sparkles: :: created saveImageList
  src/controller/user.js
  src/models/index.js
  src/models/save.js
  src/router/user.js
Labels: func, DB

#47 :bug: updated refer DB in saveImage func
  src/controller/design.js
Labels: bug

#49 :sparkles: :: created createPhoto func
  src/controller/photo.js
  src/models/photo.js
  src/router/index.js
  src/router/photo.js
  src/yarn.lock
Labels: func

#51 :sparkles: :: created readPhoto func
  src/controller/photo.js
  src/router/photo.js
Labels: func

#53 :bug: updated createPhoto func
  src/controller/photo.js
Labels: bug

#55 :sparkles: :: created deletePhoto func
  src/controller/photo.js
  src/router/photo.js
Labels: func

#57 :hammer: updated saveImage(first)
  src/controller/design.js
  src/router/design.js
  yarn.lock
Labels: update

#59 :sparkles: :: created updateSaveImage
  src/controller/design.js
  src/router/design.js
Labels: func

#61 :sparkles: :: created updatePhoto func
  src/controller/photo.js
  src/router/photo.js
Labels: func

#65 :sparkles: :: created like func
  src/controller/photo.js
  src/models/like.js
  src/router/photo.js
Labels: func, DB

#64 :bug: :: updated paramsBug fixed
  src/controller/design.js
  src/controller/photo.js
  src/controller/user.js
Labels: bug

#67 :sparkles: :: created createReport func
  src/controller/photo.js
  src/controller/report.js
  src/models/report.js
  src/router/report.js
Labels: func

#69 :sparkles: :: updated like func
  src/controller/main.js
  src/controller/photo.js
  src/router/user.js
Labels: bug

#71 :sparkles: :: created getMain func
  src/controller/main.js
  src/controller/photo.js
  src/router/index.js
  src/router/main.js
Labels: func

#74 Main sort ranking
  src/app.js
  src/controller/main.js
Labels: update

#76 :hammer: updated response structure
  src/controller/main.js
  src/controller/user.js
Labels: update

#78 :hammer: updated getMain func
  src/app.js
  src/controller/main.js
Labels: update

#82 :sparkles: :: created getLastPhoto func
  src/controller/main.js
  src/router/main.js
Labels: func

#84 :bug: :: updated JWT auth check func - middleware
  src/middleware/JWT.js
Labels: bug

#86 :sparkles: :: created search func
  src/controller/search.js
  src/router/index.js
  src/router/search.js
Labels: func

#88 :sparkles: :: created DeleteSaveImage func
  src/controller/design.js
  src/controller/photo.js
  src/controller/user.js
  src/models/like.js
  src/models/photo.js
  src/models/save.js
  src/router/design.js
  src/router/search.js
Labels: func

#91 :hammer: :: updated hadLiked value
  src/app.js
  src/controller/photo.js
  src/controller/user.js
  src/middleware/newVerify.js
  src/router/photo.js
  src/router/user.js
Labels: bug

#92 🗃️ :: updated DB : deleted createdAt & updatedAt column
  src/controller/design.js
  src/controller/main.js
  src/controller/photo.js
  src/controller/report.js
  src/controller/user.js
  src/models/like.js
  src/models/photo.js
  src/models/report.js
  src/models/save.js
  src/models/user.js
Labels: bug, DB
